=== JSenek/Eclipse-Phase-Character-Generator/backgrounds.dtd
<!DOCTYPE backgrounds [

<!ELEMENT backgrounds (background+)>
<!ELEMENT background (name,description,advantages,disadvantages,commonmorphs)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT advantages (text,skillmod*,statmod*)>
<!ELEMENT disadvantages (text,restrictedmorph*,requiredmorph?,trait*,statmod*)>
<!ELEMENT commonmorphs (text,commonmorph*)>
<!ELEMENT restrictedmorph (#PCDATA)>
<!ELEMENT requiredmorph (#PCDATA)>
<!ELEMENT restrictedtrait (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT skillmod (name,choice*,quantity?,(CPcost|amount))>
<!ELEMENT name (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT choice (#PCDATA)>
<!ELEMENT field (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT statmod (name,quantity?,amount)>
<!ELEMENT trait (#PCDATA)>
<!ELEMENT commonmorph (#PCDATA)>

]>

=== JSenek/Eclipse-Phase-Character-Generator/backgrounds.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE backgrounds SYSTEM "backgrounds.dtd">
<backgrounds>
	<background>
		<name>Drifter</name>
		<description>You were raised with a social grouping that remained on the move throughout the Sol system. This could have been free traders, pirates, asteroid farmers, scavengers, or just migrant workers. You are used to roaming space travel between habitats and stations.</description>
		<advantages>
			<text>+10 Navigation skill, +20 Pilot: Spacecraft skill, +10 Networking [Field] skill of your choice</text>
			<skillmod>
				<name>Navigation</name>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Pilot</name>
				<field>Spacecraft</field>
				<amount>20</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Networking</choice>
				<amount>10</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<commonmorphs>
			<text>All, especially Bouncers and Hibernoids</text>
			<commonmorph>Bouncer</commonmorph>
			<commonmorph>Hibernoid</commonmorph>
		</commonmorphs>
	</background>
	<background>
		<name>Fall Evacuee</name>
		<description>You were born and raised on Earth and evacuated during the horrors of the Fall, leaving your old life (and possibly your friends, family, and loved ones) behind you. You were lucky enough to survive with your body intact and continue to make a life for yourself out in the system.</description>
		<advantages>
			<text>+10 Pilot: Groundcraft skill, +10 Networking: [Field] skill of your choice, +1 Moxie</text>
			<skillmod>
				<name>Pilot</name>
				<field>Groundcraft</field>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Networking</choice>
				<amount>10</amount>
			</skillmod>
			<statmod>
				<name>MOX</name>
				<amount>1</amount>
			</statmod>
		</advantages>
		<disadvantages>
			<text>Only 2,500 Starting Credit (can still buy credit with CP)</text>
			<statmod>
				<name>CRED</name>
				<amount>-2500</amount>
			</statmod>
		</disadvantages>
		<commonmorphs>
			<text>Flats, Splicers</text>
			<commonmorph>Flat</commonmorph>
			<commonmorph>Splicer</commonmorph>
		</commonmorphs>
		</background>
	<background>
		<name>Hyper Elite</name>
		<description>You are privileged to have been raised as part of the immortal upper class that rules many inner system habitats and hypercorps. You were pampered withwealth and influence that most people can only dream of.</description>
		<advantages>
			<text>+10 Protocol skill, +10,000 Credit, +20 Networking: Hypercorps skill</text>
			<skillmod>
				<name>Protocol</name>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Hypercorps</field>
				<amount>20</amount>
			</skillmod>
			<statmod>
				<name>CRED</name>
				<amount>10000</amount>
			</statmod>
		</advantages>
		<disadvantages>
			<text>May not start with flat, splicer, or any pod, uplift, or synthetic morphs</text>
			<restrictedmorph>Flat</restrictedmorph>
			<restrictedmorph>Splicer</restrictedmorph>
			<restrictedmorph>Pod</restrictedmorph>
			<restrictedmorph>Uplift</restrictedmorph>
			<restrictedmorph>Synthetic</restrictedmorph>
		</disadvantages>
		<commonmorphs>
			<text>Exalts, Sylphs</text>
			<commonmorph>Exalt</commonmorph>
			<commonmorph>Slyph</commonmorph>
		</commonmorphs>
</background>
	<background>
		<name>Infolife</name>
		<description>You entered existence as a digital consciousness- an artificial general intelligence (AGI). Your very existence is illegal in certain habitats (a legacy of those who place the Fall at the feet of rampant AIs). Unlike the seed AIs responsible for their Fall, your capacity for self-improvement is limited, though you do have full autonomy.</description>
		<advantages>
			<text>+30 Interfacing skill, Computer skills (Infosec, Interfacing, Programming, Research) bought with Customization Points are half price</text>
			<skillmod>
				<name>Interfacing</name>
				<amount>30</amount>
			</skillmod>
			<skillmod>
				<name>Infosec</name>
				<CPcost>0.5</CPcost>
			</skillmod>
			<skillmod>
				<name>Interfacing</name>
				<CPcost>0.5</CPcost>
			</skillmod>
			<skillmod>
				<name>Programming</name>
				<CPcost>0.5</CPcost>
			</skillmod>
			<skillmod>
				<name>Research</name>
				<CPcost>0.5</CPcost>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>Real World Naiveté trait, Social Stigma (AGI) trait, may not purchase Psi trait, Social skills bought with Customization Points are double price</text>
			<trait>Real World Naiveté</trait>
			<trait>Social Stigma</trait>
			<restrictedtrait>Psi (Level 1)</restrictedtrait>
			<restrictedtrait>Psi (Level 2)</restrictedtrait>
			<skillmod>
				<name>Social</name>
				<CPcost>2.0</CPcost>
			</skillmod>
		</disadvantages>
		<commonmorphs>
			<text>Infomorphs, synthetic morphs</text>
			<commonmorph>Infomorph</commonmorph>
		</commonmorphs>
	</background>
	<background>
		<name>Isolate</name>
		<description>You were raised as part of a self-exiled grouping on the fringes of the system. Whether raised as part of a religious group, cult, social experiment, anti-tech cell, or a group that just wanted to be isolated, you spent most if not all of your upbringing isolated from other factions.</description>
		<advantages>
			<text>+20 to two skills of your choice</text>
			<skillmod>
				<name>Choice</name>
				<choice>Any</choice>
				<amount>20</amount>
				<quantity>2</quantity>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>-10 starting Rep</text>
			<statmod>
				<name>REP</name>
				<amount>-10</amount>
			</statmod>
		</disadvantages>
		<commonmorphs>
			<text>All</text>
		</commonmorphs>
	</background>
	<background>
		<name>Lost</name>
		<description>You are a legacy of one of the most infamous debacles since the Fall. As a member of the "Lost generation," you went through an accelerated-growth childhood, somehow surviving where others of your kind died, went insane, or were persecuted (see The Lost, p. 233). Your background is a social stigma, but it does provide you with certain advantages . and burdens.</description>
		<advantages>
			<text>+20 to two Knowledge skills of your choice, Psi trait (Level 1)</text>
			<skillmod>
				<name>Choice</name>
				<choice>Knowledge</choice>
				<amount>20</amount>
				<quantity>2</quantity>
			</skillmod>
			<trait>Psi (Level 1)</trait>
		</advantages>
		<disadvantages>
			<text>Mental Disorder (choose two, this includes the one from Psi) trait, Social Stigma (Lost) trait, must start with Futura morph</text>
			<trait>Mental Disorder</trait>
			<trait>Social Stigma</trait>
			<requiredmorph>Futura</requiredmorph>
		</disadvantages>
		<commonmorphs>
			<text>Futuras</text>
			<commonmorph>Futura</commonmorph>
		</commonmorphs>
	</background>
	<background>
		<name>Lunar Colonist</name>
		<description>You experienced your childhood in one of the cramped dome cities or underground stations on Luna, Earth&apos;s moon. You had a ringside seat to the Fall of Earth.</description>
		<advantages>
			<text>+10 Pilot: Groundcraft skill, +10 to one Technical, Academic: [Field], or Profession: [Field] skill of your choice, +20 Networking: Hypercorps skill</text>
			<skillmod>
				<name>Pilot</name>
				<field>Groundcraft</field>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Technical</choice>
				<choice>Academic</choice>
				<choice>Profession</choice>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Hypercorps</field>
				<amount>20</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<commonmorphs>
			<text>Flats, Splicers</text>
			<commonmorph>Flat</commonmorph>
			<commonmorph>Splicer</commonmorph>
		</commonmorphs>
	</background>
	<background>
		<name>Martian</name>
		<description>You were raised in a station on or above Mars, now the most populated planet in the system. Your home town may or may not have survived the Fall.</description>
		<advantages>
			<text>+10 Pilot: Groundcraft skill, +10 to one Technical, Academic: [Field], or Profession: [Field] skill of your choice, +20 Networking: Hypercorps skill</text>
			<skillmod>
				<name>Pilot</name>
				<field>Groundcraft</field>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Technical</choice>
				<choice>Academic</choice>
				<choice>Profession</choice>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Hypercorps</field>
				<amount>20</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<commonmorphs>
			<text>Flats, Splicers, and Rusters</text>
			<commonmorph>Flat</commonmorph>
			<commonmorph>Splicer</commonmorph>
			<commonmorph>Ruster</commonmorph>
		</commonmorphs>
	</background>
	<background>
		<name>Original Space Colonist</name>
		<description>You or your parents were part of the first "generations" of colonists/workers sent out from Earth to stake a claim in space, so you are familiar with the cramped confines of spaceflight and life aboard older stations and habitats. As a "zero-one g" (zero-gravity, firstgen), you were never part of the elite. People from your background typically have some sort of specialized tech training as vacworkers or habtechs.</description>
		<advantages>
			<text>+10 Pilot: Spacecraft or Freefall skill, +10 to a Technical, Academic: [Field], or Profession: [Field] skill of your choice, +20 to a Networking: [Field] skill of your choice</text>
			<skillmod>
				<name>Choice</name>
				<choice>Pilot</choice>
				<choice>Free Fall</choice>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Technical</choice>
				<choice>Academic</choice>
				<choice>Profession</choice>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
