=== JSenek/Eclipse-Phase-Character-Generator/factions.dtd
<!DOCTYPE factions [

<!ELEMENT factions (faction+)>
<!ELEMENT faction (name,description,advantages,disadvantages,commonmorphs)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT advantages (text,skillmod*,statmod*)>
<!ELEMENT disadvantages (text,restrictedmorph*,restrictedgear*,requiredmorph*,trait*,statmod*)>
<!ELEMENT commonmorphs (text,commonmorph*)>
<!ELEMENT restrictedmorph (#PCDATA)>
<!ELEMENT restrictedgear (#PCDATA)>
<!ELEMENT requiredmorph (#PCDATA)>
<!ELEMENT restrictedtrait (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT skillmod (name,choice*,quantity?,(CPcost|amount))>
<!ELEMENT choice (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT CPcost (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT statmod (name,quantity?,amount)>
<!ELEMENT trait (#PCDATA)>
<!ELEMENT commonmorph (#PCDATA)>

]>

=== JSenek/Eclipse-Phase-Character-Generator/factions.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE factions SYSTEM "factions.dtd">
<factions>
	<faction>
		<name>Anarchist</name>
		<description>You are opposed to hierarchy, favoring flat forms of social organization and directly democratic decisionmaking. You believe power is always corrupting and everyone should have a say in the decisions that affect their lives. According to the primitive and restrictive policies of the inner system and Jovian Junta, this makes you an irresponsible hoodlum at best and a terrorist at worst. In your opinion, that’s comedy coming from governments that keep their populations in line with economic oppression and threats of violence.</description>
		<advantages>
			<text>+10 to a skill of your choice, +30 Networking: Autonomists skill</text>
			<skillmod>
				<name>Choice</name>
				<choice>Any</choice>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Autonomists</field>
				<amount>30</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
			
		</disadvantages>
		<commonmorphs>
			<text>All</text>
			
		</commonmorphs>
	</faction>
	<faction>
		<name>Argonaut</name>
		<description>You are part of a scientific technoprogressive movement that seeks to solve transhumanity’s injustices and inequalities with technology. You support universal access to technology and healthcare, open-source models of production, morphological freedom, and democratization. You try to avoid factionalism and divisive politics, seeing transhumanity’s splintering as a hindrance to its perpetuation.</description>
		<advantages>
			<text>+10 to two Technical, Academic: [Field], or Profession: [Field] skills; +20 Networking: Scientists</text>
			<skillmod>
				<name>Choice</name>
				<choice>Technical</choice>
				<choice>Academic</choice>
				<choice>Profession</choice>
				<amount>10</amount>
				<quantity>2</quantity>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Scientists</field>
				<amount>20</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
			
		</disadvantages>
		<commonmorphs>
			<text>All</text>
			
		</commonmorphs>
	</faction>
	<faction>
		<name>Barsoomian</name>
		<description>You call the Martian outback and wilds your home. You are a “redneck,” a lower-class Martian from the rural areas that often find themselves in conflict with the policies and goals of the hypercorp domes and Tharsis League.</description>
		<advantages>
			<text>+10 Freerunning, +10 to one skill of your choice, +20 Networking: Autonomists skill</text>
			<skillmod>
				<name>Freerunning</name>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Any</choice>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Autonomists</field>
				<amount>20</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
			
		</disadvantages>
		<commonmorphs>
			<text>Cases, Flats, Rusters, Splicers, Synths</text>
			<commonmorph>Case</commonmorph>
			<commonmorph>Flat</commonmorph>
			<commonmorph>Ruster</commonmorph>
			<commonmorph>Splicer</commonmorph>
			<commonmorph>Synth</commonmorph>
		</commonmorphs>
	</faction>
	<faction>
		<name>Brinker</name>
		<description>You or your faction is reluctant to deal with the rest of the transhumanity and the various goings-on in the rest of the system. Your particular grouping may have sought out self-imposed isolation to pursue their own interests, or they may have been exiled for their unpopular beliefs. Or you may simply be a loner who prefers the vast emptiness of space to socializing with others. You might be a religious cultist, a primitivist, a utopian, or something altogether uninterested in transhumanity.</description>
		<advantages>
			<text>+10 Pilot: Spacecraft skill, +10 to a skill of your choice, +20 to a Networking: [Field] skill of your choice</text>
			<skillmod>
				<name>Pilot</name>
				<field>Spacecraft</field>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Any</choice>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Networking</choice>
				<amount>20</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
			
		</disadvantages>
		<commonmorphs>
			<text>All</text>
			
		</commonmorphs>
	</faction>
	<faction>
		<name>Criminal</name>
		<description>You are involved with the crime-oriented underworld. You may work with one of the Sol system’s major criminal factions—triads, the Night Cartel, the ID Crew, Nine Lives, Pax Familae—or one of the smaller, local operators with a big stake in a specific habitat. You might be a vetted member-for-life, a reluctant recruit, or just a freelancer looking for the next gig.</description>
		<advantages>
			<text>+10 Intimidation skill, +30 Networking: Criminal skill</text>
			<skillmod>
				<name>Intimidation</name>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Criminal</field>
				<amount>30</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
			
		</disadvantages>
		<commonmorphs>
			<text>All</text>
			
		</commonmorphs>
	</faction>
	<faction>
		<name>Extropian</name>
		<description>You are an anarchistic supporter of the free market and private property. You oppose government and favor a system where security and legal matters are handled by private competitors. Whether you consider yourself an anarcho-capitalist or a mutualist (a difference only other Extropians can figure out), you occupy a middle ground between the hypercorps and autonomists, dealing with both and yet trusted by neither.</description>
		<advantages>
			<text>+10 Persuasion skill, +20 Networking: Autonomists skill, +10 Networking: Hypercorps skill</text>
			<skillmod>
				<name>Persuasion</name>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Autonomists</field>
				<amount>20</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Hypercorps</field>
				<amount>10</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
			
		</disadvantages>
		<commonmorphs>
			<text>All</text>
			
		</commonmorphs>
	</faction>
	<faction>
		<name>Hypercorp</name>
		<description>You hail from a habitat controlled by the hypercorps. You might be a hypercapitalist entrepeneur, a hedonistic socialite, or a lowly vacworker, but you accept that certain liberties must be sacrificed for security and freedom.</description>
		<advantages>
			<text>+10 Protocol skill, +20 Networking: Hypercorps skill, +10 to any Networking: [Field] skill</text>
			<skillmod>
				<name>Protocol</name>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Hypercorps</field>
				<amount>20</amount>
			</skillmod>
			<skillmod>
				<name>Choice</name>
				<choice>Networking</choice>
				<amount>10</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
			
		</disadvantages>
		<commonmorphs>
			<text>Exalts, Olympians, Splicers, Sylphs</text>
			<commonmorph>Exalt</commonmorph>
			<commonmorph>Olympian</commonmorph>
			<commonmorph>Splicer</commonmorph>
			<commonmorph>Slyph</commonmorph>
		</commonmorphs>
	</faction>
	<faction>
		<name>Jovian</name>
		<description>Your faction is noted for its authoritarian regime, bioconservative ideologies, and militaristic tendencies. Where you come from, technology is not to be trusted and humans need to be protected from themselves. To ensure its survival, humanity must be able to defend itself and unfettered growth must be checked.</description>
		<advantages>
			<text>+10 to two weapon skills of your choice, +10 Fray, +20 Networking: Hypercorps skill</text>
			<skillmod>
				<name>Choice</name>
				<choice>Weapon</choice>
				<amount>10</amount>
				<quantity>2</quantity>
			</skillmod>
			<skillmod>
				<name>Fray</name>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Hypercorps</field>
				<amount>20</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>Must start with a Flat or Splicer morph, may not start with any nanoware/advanced nanotech</text>
			<requiredmorph>Flat</requiredmorph>
			<requiredmorph>Splicer</requiredmorph>
			<restrictedgear>Nanoware</restrictedgear>
			<restrictedgear>Advanced Nanotech</restrictedgear>
		</disadvantages>
		<commonmorphs>
			<text>Flats and Splicers</text>
			<commonmorph>Flat</commonmorph>
			<commonmorph>Splicer</commonmorph>
		</commonmorphs>
	</faction>
	<faction>
		<name>Lunar</name>
		<description>You hail from Luna, the original off-Earth colony world. Now overpopulated and in decline, Luna is one of the few places where people still cling to old-Earth ethnic and national identities. Your home is also within sight of Earth, a constant reminder that encourages many “Loonies” to be reclaimers, deploring the hypercorp interdiction and arguing that you have a right to return to Earth, terraform it, and re-establish it as a living homeworld.</description>
		<advantages>
			<text>+10 to one Language: [Field] of your choice, +20 Networking: Hypercorps skill, +10 Networking: Ecologists skill</text>
			<skillmod>
				<name>Choice</name>
				<choice>Language</choice>
				<amount>10</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Hypercorps</field>
				<amount>20</amount>
			</skillmod>
			<skillmod>
				<name>Networking</name>
				<field>Ecologists</field>
				<amount>10</amount>
			</skillmod>
		</advantages>
		<disadvantages>
			<text>None</text>
			
		</disadvantages>
		<commonmorphs>
			<text>Cases, Exalts, Flats, Splicers, Synths</text>
			<commonmorph>Case</commonmorph>
			<commonmorph>Exalt</commonmorph>
			<commonmorph>Flat</commonmorph>
			<commonmorph>Splicer</commonmorph>
			<commonmorph>Synth</commonmorph>
