=== JSenek/Eclipse-Phase-Character-Generator/morphs.dtd
<!DOCTYPE morphs [

<!ELEMENT morphs (morph+)>
<!ELEMENT morph (name,type,description,implants,mobility*,aptitudeMax,durability,woundThreshold,advantages,disadvantages,CPCost,creditCost,creditmin?,vision*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT implants (text,implant*)>
<!ELEMENT aptitudeMax (text,COG,COO,INT,REF,SAV,SOM,WIL)>
<!ELEMENT durability (#PCDATA)>
<!ELEMENT woundThreshold (#PCDATA)>
<!ELEMENT advantages (text,statmod*,aptmod*,trait*,skillmod*,armor?,size?,attack*,limbs?)>
<!ELEMENT disadvantages (text,statmod*,aptmod*,trait*)>
<!ELEMENT CPCost (#PCData)>
<!ELEMENT creditCost (#PCData)>

<!ELEMENT text (#PCDATA)>
<!ELEMENT implant (#PCDATA)>
<!ELEMENT mobility (name,walk,run)>
<!ELEMENT COG (#PCDATA)>
<!ELEMENT COO (#PCDATA)>
<!ELEMENT INT (#PCDATA)>
<!ELEMENT REF (#PCDATA)>
<!ELEMENT SAV (#PCDATA)>
<!ELEMENT SOM (#PCDATA)>
<!ELEMENT WIL (#PCDATA)>
<!ELEMENT statmod (name,quantity?,amount)>
<!ELEMENT aptmod (name,choice*,quantity?,amount)>
<!ELEMENT trait (#PCDATA)>
<!ELEMENT skillmod ((name|category),choice*,field?,quantity?,amount)>
<!ELEMENT armor (energy,kinetic)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT attack (name,dv*,skill*,field*,special*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT walk (#PCDATA)>
<!ELEMENT run (#PCDATA)>
<!ELEMENT choice (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT choice (#PCDATA)>
<!ELEMENT field (#PCDATA)>
<!ELEMENT energy (#PCDATA)>
<!ELEMENT kinetic (#PCDATA)>
<!ELEMENT limbs (#PCDATA)>
<!ELEMENT vision (#PCDATA)>

<!ATTLIST morph id ID #REQUIRED>

]>

=== JSenek/Eclipse-Phase-Character-Generator/morphs.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE morphs SYSTEM "morphs.dtd">
<morphs>
	<morph id="1">
		<name>Flat</name>
		<type>Biomorph</type>
		<description>Flats are baseline unmodified humans, born with all of the natural defects, hereditary diseases, and other genetic mutations that evolution so lovingly applies. Flats are increasingly rare—most died off with the rest of humanity during the Fall. Most new children are splicers—screened and genefixed at the least—except in habitats where flats are treated as second-class citizens and indentured labor.</description>
		<implants>
			<text>None</text>
		</implants>
		<aptitudeMax>
			<text>20</text>
			<COG>20</COG>
			<COO>20</COO>
			<INT>20</INT>
			<REF>20</REF>
			<SAV>20</SAV>
			<SOM>20</SOM>
			<WIL>20</WIL>
		</aptitudeMax>
		<durability>30</durability>
		<woundThreshold>6</woundThreshold>
		<advantages>
			<text>None</text>
		</advantages>
		<disadvantages>
			<text>None (Genetic Defects trait common)</text>
		</disadvantages>
		<CPCost>0</CPCost>
		<creditCost>High</creditCost>
	</morph>
	<morph id="2">
		<name>Splicer</name>
		<type>Biomorph</type>
		<description>Splicers are genefixed humans. Their genome has been cleansed of hereditary diseases and optimized for looks and health, but has not otherwise been substantially upgraded. Splicers make up the majority of transhumanity.</description>
		<implants>
			<text>Basic Biomods, Basic Mesh Inserts, Cortical Stack</text>
			<implant>Basic Biomods</implant>
			<implant>Basic Mesh Inserts</implant>
			<implant>Cortical Stack</implant>
		</implants>
		<aptitudeMax>
			<text>25</text>
			<COG>25</COG>
			<COO>25</COO>
			<INT>25</INT>
			<REF>25</REF>
			<SAV>25</SAV>
			<SOM>25</SOM>
			<WIL>25</WIL>
		</aptitudeMax>
		<durability>30</durability>
		<woundThreshold>6</woundThreshold>
		<advantages>
			<text>+5 to one aptitude of the player's choice</text>
			<aptmod>
				<name>Choice</name>
				<choice>Any</choice>
				<amount>5</amount>
			</aptmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<CPCost>10</CPCost>
		<creditCost>High</creditCost>
	</morph>
	<morph id="3">
		<name>Exalt</name>
		<type>Biomorph</type>
		<description>Exalt morphs are genetically enhanced humans, designed to emphasize specific traits. Their genetic code has been tweaked to make them healthier, smarter, and more attractive. Their metabolism is modified to predispose them towards staying fit and athletic for the duration of an extended lifespan.</description>
		<implants>
			<text>Basic Biomods, Basic Mesh Inserts, Cortical Stack</text>
			<implant>Basic Biomods</implant>
			<implant>Basic Mesh Inserts</implant>
			<implant>Cortical Stack</implant>
		</implants>
		<aptitudeMax>
			<text>30</text>
			<COG>30</COG>
			<COO>30</COO>
			<INT>30</INT>
			<REF>30</REF>
			<SAV>30</SAV>
			<SOM>30</SOM>
			<WIL>30</WIL>
		</aptitudeMax>
		<durability>35</durability>
		<woundThreshold>7</woundThreshold>
		<advantages>
			<text>+5 COG, +5 to three other aptitudes of the player’s choice</text>
			<aptmod>
				<name>Choice</name>
				<choice>COO</choice>
				<choice>INT</choice>
				<choice>REF</choice>
				<choice>SAV</choice>
				<choice>SOM</choice>
				<choice>WIL</choice>
				<quantity>3</quantity>
				<amount>5</amount>
			</aptmod>
			<aptmod>
				<name>COG</name>
				<amount>5</amount>
			</aptmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<CPCost>30</CPCost>
		<creditCost>Expensive</creditCost>
	</morph>
	<morph id="4">
		<name>Menton</name>
		<type>Biomorph</type>
		<description>Mentons are genetically modified to increase cognitive abilities, particularly learning ability, creativity, attentiveness, and memory. Rumors exist of superenhanced mentons with more extreme intelligence mods, but brain-hacking is notoriously difficult, and many attempts to redesign mental faculties result in impaired functioning, instability, or insanity.</description>
		<implants>
			<text>Basic Biomods, Basic Mesh Inserts, Cortical Stack, Eidetic Memory, Hyper Linguist, Math Boost</text>
			<implant>Basic Biomods</implant>
			<implant>Basic Mesh Inserts</implant>
			<implant>Cortical Stack</implant>
			<implant>Eidetic Memory</implant>
			<implant>Hyper Linguist</implant>
			<implant>Math Boost</implant>
		</implants>
		<aptitudeMax>
			<text>30</text>
			<COG>30</COG>
			<COO>30</COO>
			<INT>30</INT>
			<REF>30</REF>
			<SAV>30</SAV>
			<SOM>30</SOM>
			<WIL>30</WIL>
		</aptitudeMax>
		<durability>35</durability>
		<woundThreshold>7</woundThreshold>
		<advantages>
			<text>+10 COG, +5 INT, +5 WIL, +5 to one aptitude of the player’s choice</text>
			<aptmod>
				<name>COG</name>
				<amount>10</amount>
			</aptmod>
			<aptmod>
				<name>INT</name>
				<amount>5</amount>
			</aptmod>
			<aptmod>
				<name>WIL</name>
				<amount>5</amount>
			</aptmod>
			<aptmod>
				<name>Choice</name>
				<choice>Any</choice>
				<amount>5</amount>
			</aptmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<CPCost>40</CPCost>
		<creditCost>Expensive</creditCost>
	</morph>
	<morph id="5">
		<name>Olympians</name>
		<type>Biomorph</type>
		<description>Olympians are human upgrades with improved athletic capabilities like endurance, eye-hand coordination, and cardiovascular functions. Olympians are common among athletes, dancers, freerunners, and soldiers.</description>
		<implants>
			<text>Basic Biomods, Basic Mesh Inserts, Cortical Stack</text>
			<implant>Basic Biomods</implant>
			<implant>Basic Mesh Inserts</implant>
			<implant>Cortical Stack</implant>
		</implants>
		<aptitudeMax>
			<text>30</text>
			<COG>30</COG>
			<COO>30</COO>
			<INT>30</INT>
			<REF>30</REF>
			<SAV>30</SAV>
			<SOM>30</SOM>
			<WIL>30</WIL>
		</aptitudeMax>
		<durability>40</durability>
		<woundThreshold>8</woundThreshold>
		<advantages>
			<text>+5 COO, +5 REF, +10 SOM, +5 to one other aptitude of the player’s choice</text>
			<aptmod>
				<name>COO</name>
				<amount>5</amount>
			</aptmod>
			<aptmod>
				<name>REF</name>
				<amount>5</amount>
			</aptmod>
			<aptmod>
				<name>SOM</name>
				<amount>10</amount>
			</aptmod>
			<aptmod>
				<name>Choice</name>
				<choice>COG</choice>
				<choice>INT</choice>
				<choice>SAV</choice>
				<choice>WIL</choice>
				<amount>5</amount>
			</aptmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<CPCost>40</CPCost>
		<creditCost>Expensive</creditCost>
	</morph>
	<morph id="6">
		<name>Slyph</name>
		<type>Biomorph</type>
		<description>Sylph morphs are tailor-made for media icons, elite socialites, XP stars, models, and narcissists. Sylph gene sequences are specifically designed for distinctive good looks. Ethereal and elfin features are common, with slim and lithe bodies. Their metabolism has also been sanitized to eliminate unpleasant bodily odors and their pheromones adjusted for universal appeal.</description>
		<implants>
			<text>Basic Biomods, Basic Mesh Inserts, Clean Metabolism, Cortical Stack, Enhanced Pheromones</text>
			<implant>Basic Biomods</implant>
			<implant>Basic Mesh Inserts</implant>
			<implant>Clean Metabolism</implant>
			<implant>Cortical Stack</implant>
			<implant>Enhanced Pheromones</implant>
		</implants>
		<aptitudeMax>
			<text>30</text>
			<COG>30</COG>
			<COO>30</COO>
			<INT>30</INT>
			<REF>30</REF>
			<SAV>30</SAV>
			<SOM>30</SOM>
			<WIL>30</WIL>
		</aptitudeMax>
		<durability>35</durability>
		<woundThreshold>7</woundThreshold>
		<advantages>
			<text>Striking Looks (Level 1) trait, +5 COO, +10 SAV, +5 to one other aptitude of the player’s choice</text>
			<trait>Striking Looks (Level 1)</trait>
			<aptmod>
				<name>COO</name>
				<amount>5</amount>
			</aptmod>
			<aptmod>
				<name>SAV</name>
				<amount>10</amount>
			</aptmod>
			<aptmod>
				<name>Choice</name>
				<choice>COG</choice>
				<choice>INT</choice>
				<choice>REF</choice>
				<choice>SOM</choice>
				<choice>WIL</choice>
				<amount>5</amount>
			</aptmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<CPCost>40</CPCost>
		<creditCost>Expensive</creditCost>
	</morph>
	<morph id="7">
		<name>Bouncer</name>
		<type>Biomorph</type>
		<description>Bouncers are humans genetically adapted for zero-g and microgravity environments. Their legs are more limber, and their feet can grasp as well as their hands.</description>
		<implants>
			<text>Basic Biomods, Basic Mesh Inserts, Cortical Stack, Grip Pads, Oxygen Reserve, Prehensile Feet</text>
			<implant>Basic Biomods</implant>
			<implant>Basic Mesh Inserts</implant>
			<implant>Cortical Stack</implant>
			<implant>Grip Pads</implant>
			<implant>Oxygen Reserve</implant>
			<implant>Prehensile Feet</implant>
		</implants>
		<aptitudeMax>
			<text>30</text>
			<COG>30</COG>
			<COO>30</COO>
			<INT>30</INT>
			<REF>30</REF>
			<SAV>30</SAV>
			<SOM>30</SOM>
			<WIL>30</WIL>
		</aptitudeMax>
		<durability>35</durability>
		<woundThreshold>7</woundThreshold>
		<advantages>
			<text>Limber (Level 1) trait, +5 COO, +5 SOM, +5 to one aptitude of the player’s choice</text>
			<trait>Limber (Level 1)</trait>
			<aptmod>
				<name>COO</name>
				<amount>5</amount>
			</aptmod>
			<aptmod>
				<name>SOM</name>
				<amount>5</amount>
			</aptmod>
			<aptmod>
				<name>Choice</name>
				<choice>Any</choice>
				<amount>5</amount>
			</aptmod>
		</advantages>
		<disadvantages>
			<text>None</text>
		</disadvantages>
		<CPCost>40</CPCost>
		<creditCost>Expensive</creditCost>
	</morph>
	<morph id="8">
		<name>Fury</name>
		<type>Biomorph</type>
		<description>Furies are combat morphs. These transgenic human upgrades feature genetics tailored for endurance, strength, and reflexes, as well as behavioralmodifications for aggressiveness and cunning. To offset tendencies for unruliness and macho behavior patterns, furies feature gene sequences promoting pack mentalities and cooperation, and they tend to be biologically female.</description>
