=== JSenek/Eclipse-Phase-Character-Generator/positiveTraits.dtd
<!DOCTYPE positiveTraits [

<!ELEMENT positiveTraits (trait+)>
<!ELEMENT trait (name,type,description,choice*,skillmod*,statmod*,enables?,requires?,requiredmorph*,restrictedbg*,numcopies?,CP)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT choice (#PCDATA)>
<!ELEMENT skillmod (name,amount)>
<!ELEMENT statmod (name,amount)>
<!ELEMENT enables (#PCDATA)>
<!ELEMENT requires (#PCDATA)>
<!ELEMENT requiredmorph (#PCDATA)>
<!ELEMENT restrictedbg (#PCDATA)>
<!ELEMENT CP (#PCDATA)>

<!ELEMENT amount (#PCDATA)>

]>

=== JSenek/Eclipse-Phase-Character-Generator/positiveTraits.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE positiveTraits SYSTEM "positiveTraits.dtd">
<positiveTraits>
	<trait>
		<name>Adaptability (Level 1)</name>
		<source>Ego</source>
		<description>Resleeving is a breeze for this character. They adjust to new morphs much more quickly than most other people. Apply a +10 modifier per level for Integration Tests (p. 271) and Alienation Tests (p. 272).</description>
		<CP>10</CP>
		<enables>Adaptability (Level 2)</enables>
	</trait>
	<trait>
		<name>Adaptability (Level 2)</name>
		<source>Ego</source>
		<description>See Adaptability (Level 1)</description>
		<requires>Adaptability (Level 1)</requires>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Allies</name>
		<source>Ego</source>
		<description>The character is part of or has a relationship with some influential group that they can occasionally call on for support. For example, this could be their old gatecrashing crew, former research lab co-workers, a criminal cartel they are part of, or an elite social clique. The gamemaster and player should work out what the character?s relationship is with this group, and why the character can call on them for aid. Gamemaster?s should take care that these allies are not abused, such as calling on them more than once per game session. The character?s ties to this group are also a two-way street?they will be expected to perform duties for the group on occasion as well (a potential plot seed for scenarios).</description>
		<CP>30</CP>
	</trait>
	<trait>
		<name>Ambidextrous</name>
		<source>Ego</source>
		<description>The character can use and manipulate objects equally well with both hands (they do not suffer the off-hand modifier, as noted under Wielding Two or More Weapons, p. 206). If the character has other prehensile limbs (feet, tail, tentacles, etc.), this trait may be applied to a limb other than the hand. This trait may be taken multiple times for multiple limbs.</description>
		<CP>10</CP>
		<numcopies>Any</numcopies>
	</trait>
	<trait>
		<name>Animal Empathy</name>
		<source>Ego</source>
		<description>The character has an instinctive feel for handling and working with non-sapient animals of all kinds. Apply a +10 modifier to Animal Handling skill tests or whenever the character makes a test to influence or interact with an animal.</description>
		<skillmod>
			<name>Animal Handling</name>
			<amount>10</amount>
		</skillmod>
		<CP>5</CP>
	</trait>
	<trait>
		<name>Brave</name>
		<source>Ego</source>
		<description>This character does not scare easily and will face threats, intimidation, and certain bodily harm without flinching. As a side effect, the character is not always the best at gauging risks, especially when it comes to factoring in danger to others. The character receives a +10 modifier on all tests to resist fear or intimidation.</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Common Sense</name>
		<source>Ego</source>
		<description>The character has an innate sense of judgment that cuts through other distractions and factors that might cloud a decision. Once per game session, the player may ask the gamemaster what choice they should make or what course of action they should take, and the gamemaster should give them solid advice based on what the character knows. Alternatively, if the character is about to make a disastrous decision, the gamemaster can use the character?s free hint and warn the player they are making a mistake.</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Danger Sense</name>
		<source>Ego</source>
		<description>The character has an intuitive sixth sense that warns them of imminent threats. They receive a +10 modifier on Surprise Tests (p. 204).</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Direction Sense</name>
		<source>Ego</source>
		<description>Somehow the character always knows which way is up, north, etc., even when blinded. The character receives a +10 modifier for figuring out complex directions, reading maps, and remembering or retracing a path they have taken.</description>
		<CP>5</CP>
	</trait>
	<trait>
		<name>Eidetic Memory</name>
		<source>Ego</source>
		<description>Much like a computer, the character has perfect memory recall. They can remember anything they have sensed, often even from a single glance. This works the same as the eidetic memory implant (p. 301).</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Eidetic Memory</name>
		<source>Morph</source>
		<description>Much like a computer, the character has perfect memory recall. They can remember anything they have sensed, often even from a single glance. This works the same as the eidetic memory implant (p. 301).</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Exceptional Aptitude</name>
		<source>Ego</source>
		<description>As an ego trait, the character may raise the maximum for a particular chosen aptitude to 40 rather than 30 (p. 122). Note that this trait just raises the maximum, it does not give the character 10 more aptitude points. This trait may only be taken by a morph or ego once.</description>
		<choice>Aptitude</choice>		
		<CP>20</CP>
	</trait>
	<trait>
		<name>Exceptional Aptitude</name>
		<source>Morph</source>
		<description>As a morph trait, it raises the morph aptitude maximum (p. 124) for a particular chosen aptitude by 10 (30 for flats, 35 for splicers, 40 for all others). Note that this trait just raises the maximum, it does not give the character 10 more aptitude points. This trait may only be taken by a morph or ego once.</description>
		<choice>Aptitude</choice>
		<CP>20</CP>
	</trait>
	<trait>
		<name>Expert</name>
		<source>Ego</source>
		<description>The character is a legend in the use of one particular skill. The character may raise one learned skill over 80, to a maximum of 90, during character creation. This trait does not actually increase the skill, it just raises the maximum. This trait may only be taken once.</description>
		<choice>Skill</choice>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Fast Learner</name>
		<source>Ego</source>
		<description>The character improves skills and learns new ones in half the time it normally takes (see Improving Skills, p. 152).</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>First Impression</name>
		<source>Ego</source>
		<description>The character has a way of charming or otherwise making a good impression the first time they interact with someone. This innate social lubricant allows them to more readily deal with new contacts and slip right into new social environments. Apply a +10 modifier on social skill tests when the character is interacting with another character for the first time only.</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Hyper Linguist</name>
		<source>Ego</source>
		<description>The character has an intuitive understanding of linguistic structures that facilitates learning new languages easily. The character requires one-third the normal amount of time and experience to learn any language (see Improving Skills, p. 152). The character can also learn any human language in one day simply by constant immersive exposure to it. Additionally, the character receives a +10 modifier when attempting to interpret languages they don?t know.</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Improved Immune System (Level 1)</name>
		<source>Morph</source>
		<description>The morph?s immune system is robust and more resistant to diseases, drugs, and toxins?even more than basic biomods. At Level 1, apply a +10 modifier whenever making a test to resist infection or the effectsof a toxin or drug. This trait is only available to biomorphs.</description>
		<CP>10</CP>
		<requiredmorph>Biomorph</requiredmorph>
		<enables>Improved Immune System (Level 2)</enables>
	</trait>
	<trait>
		<name>Improved Immune System (Level 2)</name>
		<source>Morph</source>
		<description>At Level 2, increase this modifier to +20.</description>
		<CP>10</CP>
		<requires>Improved Immune System (Level 1)</requires>
	</trait>
	<trait>
		<name>Innocuous</name>
		<source>Morph</source>
		<description>In an age when exotic appearances and good looks are commonplace, the morph?s look is surprisingly bland and undistinguished, in that cookie cutter sort of way. The character?s physical looks are so mundane that others have a hard time picking them out of a crowd, describing their appearance, or otherwise remembering physical details. Apply a ?10 modifier to all tests made to spot, describe, or remember the character. This modifier does not apply to psi or mesh searches.</description>
		<CP>10</CP>
	</trait>
	<trait>
		<name>Limber (Level 1)</name>
		<source>Morph</source>
		<description>The morph is especially flexible and supple, capable of graceful contortions and interesting positions. At Level 1, the character can smoke with their toes, do the splits, and squeeze into small, cramped spaces. Each level provides a +10 modifier to escaping from bonds, fitting into narrow confines, and other acts relying on contortion or flexibility. This trait is only available to biomorphs.</description>
		<CP>10</CP>
		<requiredmorph>Biomorph</requiredmorph>
		<enables>Limber (Level 2)</enables>
	</trait>
	<trait>
		<name>Limber (Level 2)</name>
		<source>Morph</source>
		<description>At Level 2, they are double-jointed escape artists. Each level provides a +10 modifier to escaping from bonds, fitting into narrow confines, and other acts relying on contortion or flexibility.</description>
		<CP>10</CP>
		<requires>Limber (Level 1)</requires>
	</trait>
	<trait>
		<name>Math Wiz</name>
		<source>Ego</source>
