=== JSenek/Eclipse-Phase-Character-Generator/skills.dtd
<!DOCTYPE skills [

<!ELEMENT skills (skill+)>
<!ELEMENT skill (name,fields,apt,defaulting,category+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT fields (#PCDATA)>
<!ELEMENT apt (#PCDATA)>
<!ELEMENT defaulting (#PCDATA)>
<!ELEMENT category (#PCDATA)>

]>

=== JSenek/Eclipse-Phase-Character-Generator/skills.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE skills SYSTEM "skills.dtd">
<skills>
	<skill>
		<name>Academics</name>
		<fields>Yes</fields>
		<apt>COG</apt>
		<defaulting>Yes</defaulting>
		<category>Knowledge</category>
	</skill>
	<skill>
		<name>Animal Handling</name>
		<fields>No</fields>
		<apt>SAV</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Social</category>
	</skill>
	<skill>
		<name>Art</name>
		<fields>Yes</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Knowledge</category>
	</skill>
	<skill>
		<name>Beam Weapons</name>
		<fields>No</fields>
		<apt>COO</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Blades</name>
		<fields>No</fields>
		<apt>SOM</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Climbing</name>
		<fields>No</fields>
		<apt>SOM</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Physical</category>
	</skill>
	<skill>
		<name>Clubs</name>
		<fields>No</fields>
		<apt>SOM</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapons</category>
	</skill>
	<skill>
		<name>Control</name>
		<fields>No</fields>
		<apt>WIL</apt>
		<defaulting>No</defaulting>
		<category>Active</category>
		<category>Mental</category>
		<category>Psi</category>
	</skill>
	<skill>
		<name>Deception</name>
		<fields>No</fields>
		<apt>SAV</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Social</category>
	</skill>
	<skill>
		<name>Demolitions</name>
		<fields>No</fields>
		<apt>COG</apt>
		<defaulting>No</defaulting>
		<category>Active</category>
		<category>Technical</category>
	</skill>
	<skill>
		<name>Disguise</name>
		<fields>No</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Physical</category>
	</skill>
	<skill>
		<name>Exotic Melee Weapon</name>
		<fields>Yes</fields>
		<apt>SOM</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Exotic Range Weapon</name>
		<fields>Yes</fields>
		<apt>COO</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Flight</name>
		<fields>No</fields>
		<apt>SOM</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Physical</category>
	</skill>
	<skill>
		<name>Fray</name>
		<fields>No</fields>
		<apt>REF</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
	</skill>
	<skill>
		<name>Free Fall</name>
		<fields>No</fields>
		<apt>REF</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Physical</category>
	</skill>
	<skill>
		<name>Freerunning</name>
		<fields>No</fields>
		<apt>SOM</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Physical</category>
	</skill>
	<skill>
		<name>Gunnery</name>
		<fields>No</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Hardware</name>
		<fields>Yes</fields>
		<apt>COG</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Technical</category>
	</skill>
	<skill>
		<name>Impersonation</name>
		<fields>No</fields>
		<apt>SAV</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Social</category>
	</skill>
	<skill>
		<name>Infiltration</name>
		<fields>No</fields>
		<apt>COO</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Physical</category>
	</skill>
	<skill>
		<name>Infosec</name>
		<fields>No</fields>
		<apt>COG</apt>
		<defaulting>No</defaulting>
		<category>Active</category>
		<category>Technical</category>
	</skill>
	<skill>
		<name>Interest</name>
		<fields>Yes</fields>
		<apt>COG</apt>
		<defaulting>Yes</defaulting>
		<category>Knowledge</category>
	</skill>
	<skill>
		<name>Interfacing</name>
		<fields>No</fields>
		<apt>COG</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Technical</category>
	</skill>
	<skill>
		<name>Intimidation</name>
		<fields>No</fields>
		<apt>SAV</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Social</category>
	</skill>
	<skill>
		<name>Investigation</name>
		<fields>No</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Mental</category>
	</skill>
	<skill>
		<name>Kinesics</name>
		<fields>No</fields>
		<apt>SAV</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Social</category>
	</skill>
	<skill>
		<name>Kinetic Weapons</name>
		<fields>No</fields>
		<apt>COO</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Language</name>
		<fields>Yes</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Knowledge</category>
	</skill>
	<skill>
		<name>Medicine</name>
		<fields>Yes</fields>
		<apt>COG</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Technical</category>
	</skill>
	<skill>
		<name>Navigation</name>
		<fields>No</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Mental</category>
	</skill>
	<skill>
		<name>Networking</name>
		<fields>Yes</fields>
		<apt>SAV</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Social</category>
	</skill>
	<skill>
		<name>Palming</name>
		<fields>No</fields>
		<apt>COO</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Physical</category>
	</skill>
	<skill>
		<name>Perception</name>
		<fields>No</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Mental</category>
	</skill>
	<skill>
		<name>Persuasion</name>
		<fields>No</fields>
		<apt>SAV</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Social</category>
	</skill>
	<skill>
		<name>Pilot</name>
		<fields>Yes</fields>
		<apt>REF</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Vehicle</category>
	</skill>
	<skill>
		<name>Profession</name>
		<fields>Yes</fields>
		<apt>COG</apt>
		<defaulting>Yes</defaulting>
		<category>Knowledge</category>
	</skill>
	<skill>
		<name>Programming</name>
		<fields>No</fields>
		<apt>COG</apt>
		<defaulting>No</defaulting>
		<category>Active</category>
		<category>Technical</category>
	</skill>
	<skill>
		<name>Protocol</name>
		<fields>No</fields>
		<apt>SAV</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Social</category>
	</skill>
	<skill>
		<name>Psi Assault</name>
		<fields>No</fields>
		<apt>WIL</apt>
		<defaulting>No</defaulting>
		<category>Active</category>
		<category>Mental</category>
		<category>Psi</category>
	</skill>
	<skill>
		<name>Psychosurgery</name>
		<fields>No</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Technical</category>
	</skill>
	<skill>
		<name>Research</name>
		<fields>No</fields>
		<apt>COG</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Technical</category>
	</skill>
	<skill>
		<name>Scrounging</name>
		<fields>No</fields>
		<apt>INT</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Mental</category>
	</skill>
	<skill>
		<name>Seeker Weapons</name>
		<fields>No</fields>
		<apt>COO</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Sense</name>
		<fields>No</fields>
		<apt>INT</apt>
		<defaulting>No</defaulting>
		<category>Active</category>
		<category>Mental</category>
		<category>Psi</category>
	</skill>
	<skill>
		<name>Spray Weapons</name>
		<fields>No</fields>
		<apt>COO</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Swimming</name>
		<fields>No</fields>
		<apt>SOM</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Physical</category>
	</skill>
	<skill>
		<name>Throwing Weapons</name>
		<fields>No</fields>
		<apt>COO</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
	<skill>
		<name>Unarmed Combat</name>
		<fields>No</fields>
		<apt>SOM</apt>
		<defaulting>Yes</defaulting>
		<category>Active</category>
		<category>Combat</category>
		<category>Weapon</category>
	</skill>
</skills>
